sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: 4ZiScPmwb3MkTIU9kmoGcYYDKp5DUOqdGL8+UobnGm6HQsObvxB/9futi9tjTDPqebONakgSsr4lG5pLz0rRJPzgQUSDcZNlPRod0QCCuMsnT+UntWN540w11hGhrlB2G/ufR0myFSYksZuOnN/ei+cGpoST4b8w6+6f1aG55XlBC9SLG/OMIF748BY5XHYrg08mvaMTfrdU/JJcaf/GCK+a35ACLrdZM1T4nmgFSu/WHJcxVGx9OK8sEFm8asYpurPuOuIr3Wq1WTTXpim6MX0Cfnj9q9vozpUR7Oh9aNSDtwOQieIwVf5xqh5CrL5thqaOPfkRVm7duhp5fKN5shBZe4u2OsIaSo48sMnqPNv1CN91G6pC3lHUUsMW5MeNjRn2183DAI4RHw+aQo1AsWxZ5E2O6UHEKwCcXhAYWAdSikcUYQ8GIZ3Zx7dy0n8ApFCb7eolNuFXbWDdGeSpkTC05S2r6BJ5sc7kGGSwfdp/d4rkBp9lh+jPMaGxHwCKqDcQQwNLFGnMR7FryphoHvaweUf5R1bIF7Wd6+RjBiGXvMpxWfrpvi+LuPuCtMoJeTbABn2XxPsm5AFSvAH6UHF1M/BV3qvYx7/7w7PAYaR9pOBfo3wyKj0PG/7aGJiU/YOhF12WMMEctA7UvqnjlVbDR7NtGRTDEUBCxtWh8ug=
  - secure: mTj0F9vBcQIC8BKHf9/GeOx72Q3QTdCR39th9w1f3zgsPzZvB0BAZlMlqZVpRioUSH5ZJQg+TX/68WPZehuXnaHsQwb3hBzx5A7hxUnHIaPwUOnK37N1J/Q19cl37FcoBDLzcyQ4KRESF/lTzYHeLPsphnRoljP+NrtnrCLlQJMd73AYbxUtM09AXBXWSWK7eCVQmvrjPQkqWldC6rrvEuJbHpUWhbfkIugV2VPTZxmOK9KjJR04BM09xm/zUzf/Q13xmhFrWY+W5GRRufhSqvXnpJAuAQLILxV2w+VR/4IV1giR++bjS4z1kASbiu1jmbBqUj3DwL98joh7MeT0Zb41M0sZvTBTqmBN1Ph3eYHgQ7x/kTOY5acBIHEM+SbGNBqBlD9V7frv5yNHB9ikVYwdcBv4avYPIWft6Lhb9PHtjalhO99L2rxY2QmJULP2OAfibMhpwdEnHGj29WHKrKvp6Vmy+44VTY5FW+N8azY/ozZ+030N0D3+4JQZbU7hY1oS5CXBuHCnUMQNBTbTXoYSqQ9EIZ3y65bEvXpb5B1zmb2J8HaLXrujCL+5AjJH8XS2HXUhDkm9fEDhpfGPd9L5OmpX0mOW+pofN6Y9Id3/Fa+Rse6YukQsWKlKAjiNCdqkJFO7kILopJSH6K8kcwhikpRN3b9HAISrJlG9MGM=
  - secure: 0MCvtEPEqRbOV7Oxd7DRL0tE8sA6vVb5JEEb2brTyLWGKSltjb9fGFhynwv86X1/X5lPRsy6/pkL+dbuKRkI9rERcjBzPnrtCBWQi25NwcCTvUV0inAsvEZSDp778WaXw/tYJuKfUh1CWAT69c8O3VR/RFj+k0d8WtmmP5AYmp4KH8sB0KhBFOIPUMW7zzvTZ1avRNO5NgQUAM4j3FkD05b20jmGZMhRxOmsmGTS6/iKIq1tNSJKijjfhZh3zz44qO5U1EHOoLaZtgtjr/zi9Nq8Z4v5glbty+L0fAObbS6ocJ25/aN3I9Dig+AKBxEme4ylJ3yWo+9tmwEFDCT6ByH5z0gCjZSqvOTc5yubP+o9O8HKPi0pGlwOEvrxN3HP/v46cdcK58ZXnfXvGdB7GeT3qZCsdeYRehoAFqARH6B7JFUKL71pLW0QHjWTsuc5lkedPlF2rBDDsNk+RsYfYgCMfgBQ/ljBx5ISJj826dV2tiA2FtitgegbzUgev3wQn1Pie8gxcuL6tG3l5YYN6kNlVZZlKfzx2ihdSYVGZi5UDcrrdIZdq08w/yeZWrB80CrgH5nbyfX2JNkPbixlzyYKG4+Yb4JUAsjR4bJtO3S7BzqcuMdGWYqEqzdO00hjXNFYIZ5icKfkiAUzMcLN9ZBh8qj4+tAkHWnsNkh51TY=
